//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnliner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Categories1 = new HashSet<Category>();
        }
    
        public int CategoryID { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public Nullable<int> Category_CategoryID { get; set; }
        public Nullable<int> Item_mobileId { get; set; }
    
        public virtual ICollection<Category> Categories1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Item Item { get; set; }
    }
}
